
RegisterGlobalEventHandler("PlayerControlledEntityChangeEvent", function(evt)
	LogService:Log("Event" )
	local player_id = evt:GetPlayerId()
	PlayerService:AddResourceAmount(player_id, "steel", 	300000, false )
	PlayerService:AddResourceAmount(player_id, "carbonium", 300000, false )
	PlayerService:AddResourceAmount(player_id, "uranium", 	30000, false )
	PlayerService:AddResourceAmount(player_id, "titanium", 	30000, false )
	PlayerService:AddResourceAmount(player_id, "palladium", 30000, false )
	PlayerService:AddResourceAmount(player_id, "cobalt", 	30000, false )
	PlayerService:AddResourceAmount(player_id, "tanzanite", 30000, false )
	PlayerService:AddResourceAmount(player_id, "ferdonite", 30000, false )
	PlayerService:AddResourceAmount(player_id, "hazenite", 	30000, false )
	PlayerService:AddResourceAmount(player_id, "rhodonite", 30000, false )
end)